### PR TITLE
Turned on high resolution option for LSM303DLHC accelerometer, added pin...

### PR DESCRIPTION
**Pull request by mkirkhart**
...Mode() initializations for ml8511_init(), turned on temperature sensor for LSM303DLHC magnetometer, added functions for retrieving raw accelerometer, gyro, magnetometer, gyro temperature, and magnetometer temperature

### CODE REVIEW

**Comment by mkirkhart** [comment]
Ben

Yes, I have been busy over the past week or so.  If you recall, I sent you an e-mail asking about the addition of raw sensor readings and temperature from the inertial sensors (accelerometer and gyro).  Rather than going back and forth, I have cloned (or forked, in GitHub terms) the ArdusatSDK and added functions to retrieve raw readings, at least from the acclerometer, gyro, and magnetometer.  In addition, I enabled the temperature sensor on the LSM303DLHC (it turns out it is part of the magnetometer, and not the accelerometer, but at least the 2 die are inside the same packaging), and provided functions for retrieving the raw temperature from both the gyro and the magnetometer.  The scale factor on the gyro temperature is -1 LSB/degree C, but the offset is not clear.  I am not sure about the scaling and offset for the magnetometer temperature sensor; I need to retest this.

While I was at it, I found the accelerometer readings did not go up or down in increments of 1.  It turns out if you want normal (meaning high) resolution, there is a bit you need to set in one of the accelerometer control registers.  I have made this change as well, and the raw accelerometer readings now appear to have the correct resolution (can go up and down in increments of 1).  Note the scale factor has not changed (it is still configured for +/- 2g range, giving a scale factor of 1000 LSB/g), so the readings obtained from the existing engineering unit accelerometer read function will also benefit from the improved resolution.

Finally, I added the pinMode() calls for the ultraviolet sensor right in the ml8511_init() function, as this eliminates the need for the user sketch to do this.

**Comment by bencpeters** [comment]
Interesting finds! I did a little googling on the High Resolution mode and found: 

> The accelerometer gives low-resolution 10-bit readings by default (the lowest 6 bits of the output are always 0). To get the full 12-bit resolution, you must set the HR (high resolution) bit in the CTRL_REG4_A register.

So this change should indeed help things out. At some point the SDK will need to gain functionality to auto-scale and/or adjust the range/sensitivity as well, since +/- 2g isn't really suitable for all applications.

Thanks for submitting the PR! I'll test it out on some hardware tomorrow, but from glancing over it, it looks good!

**Comment by bencpeters** [comment]
Hi @mkirkhart! I had a chance to review the changes, they seem to work well. Two quick points:
- This is pretty pedantic, but I'm trying to keep commits fairly clean & atomic, with easy-to-read commit messages. Could you break this into 2 commits: 1 for the updates to the initializers for pinMode & high res mode, and one for the raw temp + raw values additions? You can do this by running `git reset ac93039`, then adding in the changes piecemeal using `git add -p`. If possible, try to keep commit messages to 80 characters or less on the first line (if you run `git commit`, it should launch you into a multi-line editor, so you can have an 80 character summary, then put details on subsequent lines)
- There's a typo in the function name `ld3gd20h_getRawTemperature`. 

Sorry to be so pedantic. The functionality looks great, I'll merge it in as soon as you update the commits!

**Comment by mkirkhart** [comment]
Ben

I think I fixed everything you wanted.  Redoing the changes as separate commits caused me some problems when I tried to push it back to the GitHub repo; it would not accept the changes, thus forcing me to do a pull - fix merge conflicts - push.

That's it for now.  Hope I got this right.

**Pull request closed without merging**
